project_id = "rmhxjagolevmlcuwxjgg"

[functions.verify-admin]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.flutterwave-nqr]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.send-notification]
verify_jwt = false
