// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxtztpuxlglvrcnhhbjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4dHp0cHV4bGdsdnJjbmhoYmpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDY3OTAsImV4cCI6MjA2MzMyMjc5MH0.RE7COzWV4nuF96TbfsZpUodS6DC1V_lL-B-L-h4uOyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);